<a href="https://colab.research.google.com/github/ADML003/AIML_repo/blob/main/AIml07_08_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
[] a = np.array([1,2,3,4])
[] a

SyntaxError: invalid syntax (<ipython-input-1-e2a153fea05d>, line 2)

In [3]:
import numpy as np

In [4]:
a= np.array([1,2,3,4])

In [5]:
b=np.array([2,3,4,2,2.2,4.4])

In [7]:
c=a+b
print(c)

ValueError: operands could not be broadcast together with shapes (4,) (6,) 

In [8]:
c=a+b

ValueError: operands could not be broadcast together with shapes (4,) (6,) 

In [10]:
d=np.array([2,3,46,4])
e=np.array([1,3,5,6])
f=d+e
print(f)

[ 3  6 51 10]


In [11]:
d=np.array([(1,2,3),(4,5,6)], dtype=float)
d

array([[1., 2., 3.],
       [4., 5., 6.]])

In [12]:
e= d=np.array([(7,3,1),(14,23,34),(13,22,34)])
e


array([[ 7,  3,  1],
       [14, 23, 34],
       [13, 22, 34]])

In [13]:
g= np.zeros((3,4))
g

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
i=np.arange(10,25,5)
i


array([10, 15, 20])

In [18]:
n =np.random.random((2,2))
n

array([[0.8969315 , 0.77924472],
       [0.76831854, 0.40173381]])